{
  "comments": [
    {
      "key": {
        "uuid": "666bd831_4669b4f3",
        "filename": "src/test/java/org/conscrypt/NativeCryptoTest.java",
        "patchSetId": 2
      },
      "lineNbr": 211,
      "author": {
        "id": 1014443
      },
      "writtenOn": "2015-03-18T20:06:44Z",
      "side": 1,
      "message": "FYI : I inspected the native code here, and i think it is incorrect.  in many cases, conscrypt code is throwing an exception from JNI when there\u0027s already an exception pending.\n\nIn particular, fromContextObject throws if the object is null. in many places we check its return value and throw again - which seems wrong.",
      "revId": "7082d33576ec909b98218a63e61f369d59be7c61",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "06a21cbf_230ef434",
        "filename": "src/test/java/org/conscrypt/NativeCryptoTest.java",
        "patchSetId": 2
      },
      "lineNbr": 211,
      "author": {
        "id": 1067467
      },
      "writtenOn": "2015-03-18T20:26:22Z",
      "side": 1,
      "message": "I don\u0027t get precisely what you mean by an \"exception pending\".\n\nI was already adding checks to fromContextObject and throwing the exception from there instead. That changes the outcome but doesn\u0027t make the problem go away.",
      "parentUuid": "666bd831_4669b4f3",
      "revId": "7082d33576ec909b98218a63e61f369d59be7c61",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "06a21cbf_63663c53",
        "filename": "src/test/java/org/conscrypt/NativeCryptoTest.java",
        "patchSetId": 2
      },
      "lineNbr": 211,
      "author": {
        "id": 1014443
      },
      "writtenOn": "2015-03-19T09:19:29Z",
      "side": 1,
      "message": "search for \"jni pending exception\" on your favourite search engine.\n\nthe summary is that \"throwing an exception\" in C++ code using JNI api doesn\u0027t have java exception semantics. The function continues to execute so care must be taken to return immediately and not make any other JNI calls until the control is ceded back to the runtime (when the function returns).",
      "parentUuid": "06a21cbf_230ef434",
      "revId": "7082d33576ec909b98218a63e61f369d59be7c61",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}